### ISSUE TITLE
FrankenPHP response isn't gzipped?

### ISSUE THREAD

**Issue by tfirdaus** [dunglas/frankenphp#707] opened 2024-04-09 07:25 UTC
### What happened?

While testing WordPress with FrankenPHP, I noticed that the response isn't actually gzipped? Take a look at these screenshots:

<img width="1137" alt="Screenshot 2024-04-09 at 3 05 35 PM" src="https://github.com/dunglas/frankenphp/assets/2067467/840fe1c8-2174-4078-9ea7-003215a8d412">

<img width="739" alt="Screenshot 2024-04-09 at 3 06 08 PM" src="https://github.com/dunglas/frankenphp/assets/2067467/9469da33-c159-42e6-87fc-a2a70a7dfe36">

As we can see there, the size of the document in FrankenPHP's response is significantly larger compared to WordPress with Apache below.👇 

<img width="1033" alt="Screenshot 2024-04-09 at 3 04 04 PM" src="https://github.com/dunglas/frankenphp/assets/2067467/72b00927-16e5-48e2-966c-a3c0c659e152">

<img width="634" alt="Screenshot 2024-04-09 at 3 04 15 PM" src="https://github.com/dunglas/frankenphp/assets/2067467/ef57b69b-4615-44d7-af5e-18a85867c089">

Both configurations are using the stock configuration from Docker WordPress and FrankenPHP. The only difference is that HTTPS redirect is disabled. Is there anything we need to configure to make it work similarly to WordPress with Apache? It would be great if we could also get the missing headers: `Content-Encoding` and `Content-Length`.

### Build Type

Docker (Debian Bookworm)

### Worker Mode

No

### Operating System

macOS

### CPU Architecture

Apple Silicon

### PHP configuration

```shell
PHP Version 8.2.17
WordPress 6.5
```

**Comment by withinboredom** [comment] 2024-04-10 19:43
Sorry to leave you hanging for so long, I've been curious how this is going on. Are you using the default caddyfile?

Can you share your request headers? Particularly the Accept-Encoding headers?

**Comment by withinboredom** [comment] 2024-04-10 19:50
Also, how are you running this? Are you running this? Is it in a docker container or cli? If a cli, can you share the incantation? If a docker container, can you share the docker file?

**Comment by withinboredom** [comment] 2024-04-11 14:05
Thank you! What are your request headers? I'd like to reproduce this and see what is going on.

**Comment by tfirdaus** [comment] 2024-04-11 14:21
@withinboredom thanks for looking into this. Here is the request header:

```
GET / HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Cookie: wordpress_test_cookie=WP%20Cookie%20check; wordpress_logged_in_5214b3dbedcdaac350d3fae0091b00b4=admin%7C1702296930%7CIR0o0bEzfHT4WQ55tElgHQKM8xCIZH05vYw7m1jndaj%7C832b1c4cd9def387253f7798a31e0e80af56119536c89c5ca9b80c69fcb4a994; wp_lang=en_US; wordpress_logged_in_902cfb915e826c1bc98213218a1bdfdd=admin%7C1702570865%7CpseSJceaiuDN4vA5ad2Y9EBhLQv8mH4HE3dxu5wmsAd%7C44f06b888f592ace3c940d8755b97fbae1cd9244470a38485cd1075d23b77791; kinsta_staff=1; __stripe_mid=2606af91-4a79-4c48-a45a-2ca2716e3e1b55b7e9; kinsta_referral=eyJhZmZpbGlhdGVfaWQiOiIyMzg5Mzg0MDMiLCJyZWZlcnJhbF9pZCI6ImFhNGE0N2M4LTRhMTgtNDRjOC1hZGE1LTZjMzI5MGVmMTQ3OSJ9; wordpress_cdc97f8e5fb252306fcf35e314d7b2aa=kinsta%7C1712216025%7Cwut1o2A3XDOXc7Xz2JIZEJB7l55deG1I7QoMeEe5pOz%7Ca50b2d7ddae208c8653ef5ab8270bff0753372d1db0c868ec75ddd57781aa168; wordpress_logged_in_cdc97f8e5fb252306fcf35e314d7b2aa=kinsta%7C1712216025%7Cwut1o2A3XDOXc7Xz2JIZEJB7l55deG1I7QoMeEe5pOz%7C44c9c5cc52d4099b46a009f76c942215a824bffcf9cf6a4f138dfdf56b458846; wp-settings-1=deleted; wp-settings-time-1=1712555209; wordpress_logged_in_812ec203ee00103a80d847d7c3d0ace6=admin%7C1712789440%7CFCr919OZm5Y2KB7h4f0NRgRDKSuCEM3jeRErulsVXJg%7Ca092077eb858fca79503aee7bbcdb10998bffea1dd4b820bc34018d9b5ba08a8
DNT: 1
Host: localhost
Pragma: no-cache
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
sec-ch-ua: "Chromium";v="123", "Not:A-Brand";v="8"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
```

**Comment by withinboredom** [comment] 2024-04-11 16:15
Yeah, this one is weird. Doing a local build of frankenphp, I see encoding working correctly. But it isn't in the docker image or static build from the latest release.

Simplest repoducer:

```php
<?php
#test.php

header('Content-Type: text/plain');
ksort($_SERVER);
var_dump($_SERVER);
```

```
./frankenphp php-server --listen :8080 &
curl -v -H "Accept-Encoding: gzip" localhost:8080/test.php
```

You should see the following output:

```
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /test.php HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: */*
> Accept-Encoding: gzip
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Encoding: gzip
< Content-Type: text/plain;charset=UTF-8
< Server: Caddy
< Vary: Accept-Encoding
< X-Powered-By: PHP/8.3.4-dev
< Date: Thu, 11 Apr 2024 16:14:21 GMT
< Transfer-Encoding: chunked
<
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
* Failure writing output to destination
* Failed reading the chunked-encoded stream
* Closing connection 0
```

@dunglas any idea why CI builds wouldn't be encoding output? I'm kinda scratching my head on this one.

**Comment by dunglas** [comment] 2024-04-11 16:50
Is the `Content-Length` missing or the response size too small to trigger the encoder?

**Comment by withinboredom** [comment] 2024-04-11 16:55
Same output in both cases, very strange

https://asciinema.org/a/wmiKh5LBDImSJ2WwwsWaF7KrV

**Comment by dunglas** [comment] 2024-04-15 15:47
I also reproduce the issue locally. So far, I've no idea of what's going on.

**Comment by dunglas** [comment] 2024-04-15 16:26
I cannot reproduce the issue on Mac using the official Docker image (Linux ARM) or the Mac ARM binary running directly on the host.

**Comment by StephenMiracle** [comment] 2024-05-11 21:27
hey! I’m a little late. i know gzip is working correctly on the frankenwp image. Have you checked  this repo? 
the default is brotli but also supports gzip as backup.

https://github.com/StephenMiracle/frankenwp

@tfirdaus

**Comment by dunglas** [comment] 2024-05-13 11:36
I am closing for now as we haven't reproduced the issue yet.


Feel free to reopen if you can provide a minimal reproducer.

**Closed by dunglas** 2024-05-13 11:36 UTC
Labels: bug
