### ISSUE TITLE
file_get_contents(): SSL operation failed with code 5. OpenSSL Error - Laravel octane

### ISSUE THREAD

**Issue by degodfather** [dunglas/frankenphp#679] opened 2024-03-20 16:21 UTC
### What happened?

While using file_get_contents() to fetch an https url, I'm getting the following error 

`file_get_contents(): SSL operation failed with code 5. OpenSSL Error messages:
error:80000002:system library::No such file or directory
error:80000002:system library::No such file or directory
error:80000002:system library::No such file or directory
error:0A000086:SSL routines::certificate verify failed `

I'm using Laravel Octane and I'm able to fetch https URL using file_get_contents() using PHP cli 

### Build Type

Standalone binary

### Worker Mode

Yes

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
Interesting thing phpinfo() doesn't return anything on the server.
```

### Relevant log output

```shell
file_get_contents(): SSL operation failed with code 5. OpenSSL Error messages:
error:80000002:system library::No such file or directory
error:80000002:system library::No such file or directory
error:80000002:system library::No such file or directory
error:0A000086:SSL routines::certificate verify failed
```

**Comment by dunglas** [comment] 2024-03-20 17:01
Duplicate of https://github.com/dunglas/frankenphp/issues/582.

**Closed by dunglas** 2024-03-20 17:01 UTC
Labels: bug
