### ISSUE TITLE
frankenphp_worker_php_ready_worker is skewing to negative values with worker restarts

### ISSUE THREAD

**Issue by LauJosefsen** [dunglas/frankenphp#1163] opened 2024-11-14 17:13 UTC
### What happened?

Hi.

We have excitingly been trying out the new 1.3.0 release. We immediately setup an alert on the `frankenphp_worker_php_ready_worker` metric on our environments.

We however observed that this metric has a decreasing pattern to it, that is not equal to the relationship of `total_workers - busy_workers`.

Look at this plot of the metric of a somewhat busy container (20RPS ish) (each line is a seperate container)

![image](https://github.com/user-attachments/assets/adbf12a1-3d4e-4489-bcb1-af5df5503f25)

I was very worried of this metric, however it has now become a negative value, indicating that is keep decreasing even below 0. In our case we may see the ready_worker metric report -2, while the busy worker metric is 4 and total workers is 60. So in this case I assume the correct value is 56? Or close to 56.

It looks to be somewhat correlated to worker restarts, looking at this graph: 

![image](https://github.com/user-attachments/assets/3a6f9f3d-c8f9-45b7-bf0b-4f60566933ca)

The service is responding as normal even with negative ready workers

### Build Type

Docker (Debian Bookworm)

### Worker Mode

Yes

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
Not relevant
```

**Comment by AlliBalliBaba** [comment] 2024-11-15 12:54
Yeah it looks like [ReadyWorker](https://github.com/dunglas/frankenphp/blob/a441e22a1bc06c49154a153d8137ec9050a03081/worker.go#L257) is only called once, while [StopWorker](https://github.com/dunglas/frankenphp/blob/a441e22a1bc06c49154a153d8137ec9050a03081/worker.go#L159) is called every time a worker restarts, skewing the metric.
@withinboredom after #1137 this could maybe also be refactored to pull metrics instead of pushing them, since we can just loop over all workers and the threads assigned to them.

**Comment by withinboredom** [comment] 2024-11-15 14:02
This is possibly a merge-conflict resolution error on my part, but at a glance, it appears to be working as designed.

It is stopping workers, then it calls `initWorkers`, which should eventually call `startNewWorkerThread`, which should call `metrics.StartWorker(worker.fileName)`, which should increment the worker count back up.

I think something is missing here.

> this could maybe also be refactored to pull metrics instead of pushing them

I don't know how I would feel about a God System reaching into things just to extract metrics.

**Comment by withinboredom** [comment] 2024-11-15 14:07
> I think something is missing here.

Aha!

`frankenphp_worker_php_ready_worker`, per the documentation: 

> The number of workers that have called frankenphp_handle_request at least once.

This should be a static number once started. It doesn't (usually) increase. It is indicative of a successful startup, not part of request handling itself.

**Comment by withinboredom** [comment] 2024-11-15 19:50
ah, yeah. The metric changed meaning during the merge conflict. I'll fix it.

**Closed** 2024-11-21 12:23 UTC
Labels: bug
