### ISSUE TITLE
No output in latest version

### ISSUE THREAD

**Issue by withinboredom** [dunglas/frankenphp#177] opened 2023-08-06 18:59 UTC
I don't have a simple reproduction case, but this causes nothing to be output when deep in the stack:

```php

if(ob_get_level()> 0 && ob_get_length() > 0) {
	echo 'true';
}
```

If and only if those two conditions are on the same line (and if-statement) does it cause all output to cease functioning. Breaking them up into multiple if-statements is enough to allow processing to continue.

I'll bisect and try to hunt down the specific version this broke in. All I know is that it wasn't broken in 

```
frankenphp version

FrankenPHP main Caddy v2.6.4 h1:2hwYqiRwk1tf3VruhMpLcYTg+11fCdr8S3jhNAdnPy8=

```

**Comment by withinboredom** [comment] 2023-08-06 19:55
Ok, red herring. Here's the minimal reproduction case.

```php
<?PHP

echo 'hello world';
flush();

// never executes
throw new LogicException('expected unhandled exception');
```

**Comment by withinboredom** [comment] 2023-08-06 20:22
There's very clearly a test case for this in the repo and it works. After digging a little deeper when I removed:

```
RUN mv $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini
```

from my Dockerfile, it magically started working as it did before. So now I'm trying to figure out which ini setting causes it to misbehave.

**Comment by withinboredom** [comment] 2023-08-06 20:29
Looks like if there is output buffering, a `flush()` doesn't work.

**Comment by withinboredom** [comment] 2023-08-06 20:56
When adding some logging to `go_sapi_flush()`:

```go
	flusher, ok := fc.responseWriter.(http.Flusher)
	if !ok {
	    fc.Logger.Info("response writer is not a flusher")
		return true
	}
```

I get the output:

```
{"level":"info","ts":1691355272.3962996,"logger":"http.handlers.php","msg":"response writer is not a flusher"}
```

**Comment by withinboredom** [comment] 2023-08-06 20:58
Ah, it looks like http3 doesn't support the Flush interface. 😂

**Comment by withinboredom** [comment] 2023-08-06 21:04
Potentially a bug with caddy 2.6 vs. 2.7?

**Comment by dunglas** [comment] 2023-08-06 22:00
Maybe related to https://github.com/caddyserver/caddy/pull/5509?

**Comment by dunglas** [comment] 2023-08-07 21:28
It's not related to https://github.com/caddyserver/caddy/pull/5509 after all.

The problem is that if the `log` directive is enabled, the  `caddyhttp.ResponseRecorder` is used and it doesn't support streaming/`http.Flusher`. Removing the directive fixes the issue.
There is also another bug in FrankenPHP fixed in #179.

 I don't know if this changed in Caddy 2.7, and it's expected. Maybe @mholt has a hint about this?

**Comment by mholt** [comment] 2023-08-07 21:30
To be sure, are you using Caddy 2.7.3?

**Comment by dunglas** [comment] 2023-08-07 21:34
2.7.2 until #178 is merged, but I just tested and the problem also exists in 2.7.3.

**Comment by dunglas** [comment] 2023-08-07 21:54
I cannot check right now but it's probably related to the ordering because with FrankenPHP using an ordered route is mandatory. @withinboredom could you try putting the log directive last?

**Comment by francislavoie** [comment] 2023-08-07 22:34
The log directive isn't an HTTP handler directive, it sets up server-level config. Ordering is not the problem.

I think it does have to do with ResponseController stuff. Was the PHP handler updated to use ResponseController to call Flush()? It would need to, to unwrap the underlying flusher.

**Comment by mholt** [comment] 2023-08-07 22:34
@dunglas I wish that were the case, but I think it's unlikely, since `log` is actually a directive that controls the HTTP server itself.

**Comment by francislavoie** [comment] 2023-08-07 22:37
Yeah, https://github.com/dunglas/frankenphp/blob/main/frankenphp.go#L568 needs to be updated to use ResponseController I think.

**Comment by mholt** [comment] 2023-08-07 22:46
Sorry. I didn't realize this was a breaking change. :confounded:

**Closed** 2023-08-12 19:25 UTC
